version: "3.8"

services:
  database:
    image: mysql:8.0
    container_name: mysql-db
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: IncidentManagementSystem
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./Backend/IncidentReportingSys
    container_name: IMS-BackendApp
    #restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/IncidentManagementSystem
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  frontend:
    build: ./Frontend/incidentReportingSys
    container_name: IMS-FrontendApp
    #restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data:
